### ISSUE TITLE
Tracing seems to be enabled be default in HTTP examples

### ISSUE THREAD

**Issue by scholzj** [strimzi/client-examples#118]
I deployed the HTTP consumer example with the following YAML:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-http-consumer
  name: java-http-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-http-consumer
  template:
    metadata:
      labels:
        app: java-http-consumer
    spec:
      containers:
      - name: java-http-consumer
        image: quay.io/strimzi-examples/java-http-consumer:latest
        env:
          - name: STRIMZI_HOSTNAME
            value: my-bridge-bridge-service
          - name: STRIMZI_PORT
            value: "8080"
          - name: STRIMZI_TOPIC
            value: kafka-test-apps
          - name: STRIMZI_GROUPID
            value: "my-group"
          - name: STRIMZI_POLL_INTERVAL
            value: "1000"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "250m"
```

So I did not enable tracing. Yet, it seems to be enabled by default as I get this in the logs:
```
Mar 11, 2023 8:07:00 PM io.opentelemetry.sdk.internal.ThrottlingLogger doLog
SEVERE: Failed to export metrics. The request could not be executed. Full error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
```

So it seems like the tracing is permanently enabled. This should be fixed and it should be enabled only when specified in the Deployment.
